### ISSUE TITLE
Upgrade to `cryptography ~= 44.0`

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/rfc3161-client#74]
cryptography 44 removes a bunch of ABCs that we currently use, so this will be a non-trivial bump.

xref https://github.com/sigstore/sigstore-python/issues/1231 (this is not related directly to the breakage there, since the TSA changes haven't landed in a release yet).

**Comment by DarkaMaul** [comment]
I've updated dependabot's PR https://github.com/trailofbits/rfc3161-client/pull/75/files but I think we are already good because we don't use any of the removed APIs.

**Comment by woodruffw** [comment]
#75
