### ISSUE TITLE
Incorrect runtime dependency on maturin

### ISSUE THREAD

**Issue by mgorny** [trailofbits/rfc3161-client#86]
The package lists `maturin` in `dependencies`. This is incorrect, since Maturin is only a build system, and it is not used in the package after installation. As a result, everyone who does `pip install rfc3161-client` (from wheels) gets `maturin` unnecessarily installed on their system.

**Comment by DarkaMaul** [comment]
Thanks for your report. Indeed, that was an oversight on my end.

I've opened a PR that fixes it.
